### ISSUE TITLE
Make it work with NPM?

### ISSUE THREAD

**Issue by bettiolo** [websanova/js-url#28]
It would be very good to have the library work in node. Any plans?

**Comment by ssreekanth** [comment]
@websanova, did you get any chance to make this library work with npm/node?

**Comment by websanova** [comment]
Yep, it's already there.

https://github.com/websanova/node-url

**Comment by ssreekanth** [comment]
I found it already, hence deleted my comment. This issue made me think that its not done yet. You should probably close this issue.

**Comment by bettiolo** [comment]
Thanks everyone :+1:
