### ISSUE TITLE
alternate URI schemes

### ISSUE THREAD

**Issue by thedamon** [websanova/js-url#33]
I noticed that `url('protocol', 'mailto:jim@flaubert.com')` returns `http`.

Is there any way to detect for 'non-web' URI schemes? (not sure on the exact nomenclature)

**Comment by websanova** [comment]
Just added support for this in v2.0.0 release :-)

url('protocol', 'mailto:rob@websanova.com'); // mailto
url('email', 'mailto:rob@websanova.com'); // rob@websanova.com
