### ISSUE TITLE
Publish a bower package

### ISSUE THREAD

**Issue by ssreekanth** [websanova/js-url#37]
It would be nice to have a bower package for js-url library.

Publishing in [bower](http://bower.io) would make it easier to find and install js-url.js library.

**Comment by websanova** [comment]
Yes, thx for reminding me, I will get to this shortly.

**Comment by websanova** [comment]
Ok, I added a `bower.json` file, but when I try to register the package it says duplicate. But if you search bower it doesn't show up. However `bowers install js-url` works, but doesn't pick up the `main` and `ignores` parameters.

Anyway, I've never had much luck with bower, I don't think I've ever run a command without getting some kind of error or warning so I generally just avoid it out of frustration. Not sure if this will work for anyone, so I'll try to sort it out over SO and leave the issue open for now.

**Comment by ssreekanth** [comment]
Works fine for me. This is what I get, when I run `bower install js-url`
```
$ bower install js-url

bower js-url#*              not-cached git://github.com/websanova/js-url.git#*
bower js-url#*                 resolve git://github.com/websanova/js-url.git#*
bower js-url#*                download https://github.com/websanova/js-url/archive/v2.0.2.tar.gz
bower js-url#*                 extract archive.tar.gz
bower js-url#*                resolved git://github.com/websanova/js-url.git#2.0.2
bower js-url#~2.0.2            install js-url#2.0.2

js-url#2.0.2 renderer\bower_components\js-url

$ ls
bower.json  README.md  url.js  url.min.js  url-tld.min.js
```

**Comment by websanova** [comment]
Ok, cool :-)
