### ISSUE TITLE
can not got query param when there's multiple ? eg: http://xxx.com?k=v#/a/b?k2=v2

### ISSUE THREAD

**Issue by xiwc** [websanova/js-url#40]

**Comment by websanova** [comment]
Not sure what you're asking:

~~~
`console.log(window.url('?', 'http://xxx.com?k=v#/a/b?k2=v2')); // {k: "v"}`
`console.log(window.url('#', 'http://xxx.com?k=v#/a/b?k2=v2')); // {/a/b?k2: "v2"}`
~~~

This is behaving properly. It will parse at the first `?`. Also the second one is after the `#` so it's separate parsing there which is not supported in the script.

You may have to do some manual parsing:

~~~
var hash = str.split('#')[1]; //  '/a/b?k2=v2'

console.log(window.url('?',hash)); // {k2: "v2"}
console.log(window.url('/', hash)); // ["a", "b"]
~~~

**Comment by xiwc** [comment]
var s = 'http://example.com/index.html#/project/ff8081815070fa4c0150734af2871482/task-pane?code=c8125974b528718ef9d29f2ac852fe18&accessToken=RUwwZjJvdWFiOWtXa2F6NnV1c1BiWTg4LzFKQXo3ekVZYlBIYU9raTFxM2M5MWtTK3FNV0dFcEpoUnV4b3pmTVdTL1ltcVExY3M4WncvT2t2TlkyUU5YUklXbVNpN0ZCV3p1TTJYZlNEMVVRVWtYT2kveHMwbnZoQUcwM1ZGckk=';

url('#', s);

"/project/ff8081815070fa4c0150734af2871482/task-pane?code=c8125974b528718ef9d29f2ac852fe18&accessToken=RUwwZjJvdWFiOWtXa2F6NnV1c1BiWTg4LzFKQXo3ekVZYlBIYU9raTFxM2M5MWtTK3FNV0dFcEpoUnV4b3pmTVdTL1ltcVExY3M4WncvT2t2TlkyUU5YUklXbVNpN0ZCV3p1TTJYZlNEMVVRVWtYT2kveHMwbnZoQUcwM1ZGckk="

but i only want to get `/project/ff8081815070fa4c0150734af2871482/task-pane` without query string.

**Comment by websanova** [comment]
Try url('/', s);

**Comment by xiwc** [comment]
does not work:
![image](https://cloud.githubusercontent.com/assets/8816203/10556823/5d37f150-74c3-11e5-812d-79a9754da70b.png)

my using url version:
![image](https://cloud.githubusercontent.com/assets/8816203/10556824/66931824-74c3-11e5-8d34-5fdc69d959ea.png)

**Comment by websanova** [comment]
Can you upgrade to latest version?

**Comment by xiwc** [comment]
Very 3ks, i saw the 2.x version, i will try.
