### ISSUE TITLE
unreachable code after return

### ISSUE THREAD

**Issue by ernscht** [websanova/js-url#46]
Hi Rob
Can you please take a look on [this line](https://github.com/websanova/js-url/blob/master/url.js#L4)?
Thanks for your work.

**Comment by websanova** [comment]
Not sure what you mean.

Rob

On Sun, Mar 6, 2016 at 4:04 AM, Ernst Ammann <notifications@github.com>
wrote:

> Hi Rob
> Can you please take a look on this line
> <https://github.com/websanova/js-url/blob/master/url.js#L4>?
> Thanks for your work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/websanova/js-url/issues/46>.
>



-- 
Robert Duchnik
http://www.duchnik.com

**Comment by websanova** [comment]
Nevermind, found it, there was a `;` typo.
