### ISSUE TITLE
Seems like url('domain' ..  always return undefined

### ISSUE THREAD

**Issue by linuxenko** [websanova/js-url#47]

**Comment by websanova** [comment]
Try hostname.

**Comment by linuxenko** [comment]
'hostname' work just fine. i though  'domain'  will return hostname without 'www' or any other top level things . ok , it's difficult stuff , i understand .

**Comment by websanova** [comment]
You only get domains if you use the tld version. Otherwise it will return
undefined.

https://github.com/websanova/js-url/blob/master/url.js#L163
