### ISSUE TITLE
TLD list needs to be updated!

### ISSUE THREAD

**Issue by tobsn** [websanova/js-url#49]
example.plus
=> pl.us

Current list of TLDs:
http://data.iana.org/TLD/tlds-alpha-by-domain.txt

**Comment by websanova** [comment]
Yes, the problem is that the full list is a bit long now. Would be nice to separate them in some way, like by country and full lists, but can't any good source for this.

**Comment by websanova** [comment]
Seems like that list is also missing some things like "co.uk".

**Comment by websanova** [comment]
Adding for reference:

https://publicsuffix.org/list/public_suffix_list.dat
