### ISSUE TITLE
grunt-contrib-* should be put into devDependencies

### ISSUE THREAD

**Issue by hustcer** [websanova/js-url#51]
```
"dependencies": {
    "grunt-contrib-qunit": "",
    "grunt-contrib-uglify": "",
    "grunt-contrib-jshint": ""
  },
```

`grunt-contrib-*` should be put into `devDependencies` not `dependencies`

**Comment by websanova** [comment]
Thx, updated.

**Comment by hustcer** [comment]
It would be better to publish it to npm registry, IMO.

**Comment by websanova** [comment]
There is a node version already, it's mentioned in the docs:

https://github.com/websanova/js-url

**Comment by hustcer** [comment]
@websanova  I know that, but it should be updated, since the `package.json` has been modified.

**Comment by websanova** [comment]
Hmm, updated on npm? Well the `wurl` package has no dependencies. And the
js-url one only exists on github which is already updated. So not sure what
you mean.

**Comment by hustcer** [comment]
Sorry, my mistake, I'm using the npm package: `js-url`

**Comment by websanova** [comment]
ya, that's not official one. I didn't even know that was there. :P

**Comment by Gcaufy** [comment]
FYI: https://github.com/WillZWL/js-url/pull/2

**Comment by websanova** [comment]
I'm thinking I should just move it to @websanova/js-url which I started doing for all my packages there. It's kind of a mess with npm that they don't enforce namespacing.

**Comment by Gcaufy** [comment]
I suggest you send an email to npmsupport, Ask them to help you to get back the npm package. 
And they will do.

**Comment by websanova** [comment]
Ok, I sent them an email, let's see what happens.

**Comment by Gcaufy** [comment]
> Ok, I sent them an email, let's see what happens.

So what did the npm support says?

**Comment by websanova** [comment]
To be honest, not sure, kind of forgot about this one.

I've since updated this so that all versions are available at 

https://www.npmjs.com/package/@websanova/url

https://github.com/websanova/js-url
