### ISSUE TITLE
.NET NuGet Package

### ISSUE THREAD

**Issue by davyfarr** [websanova/js-url#53]
Would you be so kind to release a nuget package for .NET?
Thx!

**Comment by websanova** [comment]
lol, I don't even know what that is :p

**Comment by farda23** [comment]
Oh well, it's a free package manager for Microsoft .NET libraries like bower for Java.
Here's the link: https://www.nuget.org/
But don't bother, if you have time and wish to do it, it could be useful, othrewise nevermind. I'll deal with that.

**Comment by davyfarr** [comment]
Oh well, it's a free package manager for Microsoft .NET libraries like bower for Java.
Here's the link: https://www.nuget.org/
But don't bother, if you have time and wish to do it, it could be useful, othrewise nevermind. I'll deal with that.
