### ISSUE TITLE
some domains is not defined

### ISSUE THREAD

**Issue by gizmooo** [websanova/js-url#61]
The domain-first domain approach is incorrect. For example, goo.gl returns undefined

**Comment by websanova** [comment]
Are you using to version?

Also note that it's not a full to list as there are literally thousands of
them nowadays.

**Comment by gizmooo** [comment]
I'm using the latest version of the plugin.
How do I get a domain?
https://plnkr.co/edit/YWy7BYrPxvGhW6F5aH3i?p=preview

**Comment by websanova** [comment]
*I meant TLD version...

https://github.com/websanova/js-url/blob/master/url-tld.min.js

**Comment by gizmooo** [comment]
Same thing with this version.
Can i do something wrong?
https://plnkr.co/edit/F4QlagpjcJNTBHKIfp8m?p=preview

**Comment by websanova** [comment]
Show your code

**Comment by gizmooo** [comment]
`var LINK = 'https://goo.gl/maps/smEKk1kZtq72'
  var domain = url('domain', LINK);
  var hostname = url('hostname', LINK);`

**Comment by websanova** [comment]
Ok, so I added "gl" to the domain list. But that will only solve the issue with this domain.

I kind of gave up on keeping the tld list up to date because there are just too many nowadays.

You might want to try using the `url('.-1)` type structure for domain parts.
