### ISSUE TITLE
Works incorrect in case of using wiredep grunt task

### ISSUE THREAD

**Issue by ravbetsky** [websanova/js-url#69]
Hello, 

Auto injection through wiredep doesn't work because main field of `bower.json` stores the path to non-existing file https://github.com/websanova/js-url/blob/master/bower.json#L11

**Comment by websanova** [comment]
Not sure what the title means, but update the bower file. I'm not using bower so hopefully that works `v2.6.2`

**Comment by ravbetsky** [comment]
Thanks!

**Comment by ravbetsky** [comment]
@websanova One moment `./dist/es5-url-min.js` should be `./dist/es5-url.min.js` I suppose

**Comment by websanova** [comment]
ok, fixed @ravbetsky
